---
title: "Cluster images"
output: html_document
---

```{r}
library(keras)
library(magick)  # for preprocessing images
```

```{r}
model <- application_vgg16(weights = "imagenet", include_top = FALSE)
model
```

```{r}
image_prep <- function(x) {
  arrays <- lapply(x, function(path) {
    img <- image_load(path, target_size = c(224,224))
    x <- image_to_array(img)
    x <- array_reshape(x, c(1, dim(x)))
    x <- imagenet_preprocess_input(x)
  })
  do.call(abind::abind, c(arrays, list(along = 1)))
}
```

```{r}
image_files_path <- "/Users/shiringlander/Documents/Github/Data/Dataset_mshack/MaleVsFemaleBikes"
img_path <- file.path(image_files_path, "Female", 'bike_008.bmp')
img_path2 <- file.path(image_files_path, "Others", 'bike_001.bmp')
```

```{r}
vgg16_feature <- predict(model, image_prep(img_path))
```

```{r}
dim(vgg16_feature)
```

```{r}
flatten <- as.data.frame.table(vgg16_feature, responseName = "value") %>%
  select(value)
flatten <- cbind(img_path, as.data.frame(t(flatten)))
flatten[, 1:10]
```

```{r}
file_list <- list.files(image_files_path, full.names = TRUE, recursive = TRUE)
```

```{r eval=FALSE}
vgg16_feature_list <- data.frame()

for (image in file_list) {
  
  vgg16_feature <- predict(model, image_prep(image))
  
  flatten <- as.data.frame.table(vgg16_feature, responseName = "value") %>%
    select(value)
  flatten <- cbind(image, as.data.frame(t(flatten)))
  
  vgg16_feature_list <- rbind(vgg16_feature_list, flatten)
}
head(vgg16_feature_list)
dim(vgg16_feature_list)
save(vgg16_feature_list, file = "vgg16_feature_list.RData")
```

```{r}
load("vgg16_feature_list.RData")
```

```{r}
pca <- prcomp(vgg16_feature_list[, -1],
              center = TRUE,
              scale = FALSE)

str(pca)
```

```{r}
cluster <- kmeans(pca$x[, 1:10], 2)

cluster_list <- data.frame(cluster = cluster$cluster, vgg16_feature_list) %>%
  select(cluster, image)
head(cluster_list)
```

```{r}
cluster_list %>%
  mutate(class = gsub("/Users/shiringlander/Documents/Github/Data/Dataset_mshack/MaleVsFemaleBikes/", "", image),
         class = substr(class, start = 1, stop = 3)) %>%
  count(cluster, class)
```

```{r}
cluster_list %>%
  mutate(PC1 = pca$x[, 1],
         PC2 = pca$x[, 2],
         class = gsub("/Users/shiringlander/Documents/Github/Data/Dataset_mshack/MaleVsFemaleBikes/", "", image),
         class = substr(class, start = 1, stop = 3)) %>%
  ggplot(aes(x = PC1, y = PC2, color = class)) +
    geom_point()
```

