---
title: "MSHack Keras tests"
output: html_document
---

```{r}
library(keras)
library(tidyverse)
```

```{r}
bike_list <- c("Female", "Others")

img_width <- 100
img_height <- 100
target_size <- c(img_width, img_height)

# RGB = 3 channels
channels <- 3

# path to image folders
train_image_files_path <- "/Users/shiringlander/Documents/Github/Data/Dataset_mshack/MaleVsFemaleBikes"
```

```{r}
train_data_gen = image_data_generator(
  rescale = 1/255,
  validation_split = 0.3,
  rotation_range = 40,
  width_shift_range = 0.2,
  height_shift_range = 0.2,
  shear_range = 0.2,
  zoom_range = 0.2,
  horizontal_flip = TRUE,
  fill_mode = "nearest"
)
```

```{r}
train_image_array_gen <- flow_images_from_directory(train_image_files_path, 
                                          train_data_gen,
                                          subset = 'training',
                                          target_size = target_size,
                                          class_mode = "binary",
                                          classes = bike_list,
                                          seed = 42)
```

```{r}
valid_image_array_gen <- flow_images_from_directory(train_image_files_path, 
                                          train_data_gen,
                                          subset = 'validation',
                                          target_size = target_size,
                                          class_mode = "binary",
                                          classes = bike_list,
                                          seed = 42)
```

```{r}
cat("Number of images per class:")
table(factor(train_image_array_gen$classes))
table(factor(valid_image_array_gen$classes))
```

```{r eval=FALSE}
grid <- expand.grid(filter_1 = c(4, 8, 16),
                    filter_2 = c(4, 8, 16),
                    dense_nodes = c(2, 4, 10))
grid
```

```{r}
train_samples <- train_image_array_gen$n
valid_samples <- valid_image_array_gen$n
batch_size <- 8
epochs <- 10

for (i in 1:20) {
  filter_1 <- base::sample(grid$filter_1, 1)
  filter_2 <- base::sample(grid$filter_1, 1)
  dense_nodes <- base::sample(grid$dense_nodes, 1)

  # initialise model
  model <- keras_model_sequential() %>%
    
    layer_conv_2d(filter = filter_1, kernel_size = c(3, 3), padding = "same", input_shape = c(img_width, img_height, channels)) %>%
    layer_activation("relu") %>%
    
    # Second hidden layer
    layer_conv_2d(filter = filter_2, kernel_size = c(3, 3), padding = "same") %>%
    layer_activation("relu") %>%
    layer_batch_normalization() %>%
  
    # Use max pooling
    layer_max_pooling_2d(pool_size = c(2, 2)) %>%
    layer_dropout(0.5) %>%
    
    # Flatten max filtered output into feature vector 
    # and feed into dense layer
    layer_flatten() %>%
    layer_dense(dense_nodes) %>%
    layer_activation("relu") %>%
    layer_dropout(0.5) %>%
  
    # Outputs from dense layer are projected onto output layer
    layer_dense(1) %>% 
    layer_activation("softmax") %>% 
    
    # compile
    compile(loss = "binary_crossentropy",
            optimizer = optimizer_adamax(),
            metrics = c("accuracy", "mse")) %>% 
    
    fit_generator(
      # training data
      train_image_array_gen,
      
      # epochs
      steps_per_epoch = as.integer(train_samples / batch_size), 
      epochs = epochs, 
      
      validation_data = valid_image_array_gen,
      validation_steps = as.integer(valid_samples / batch_size),
      
      # print progress
      verbose = 2,
      callbacks = list(
        # save best model after every epoch
        callback_model_checkpoint("/Users/shiringlander/Documents/Github/MSHackRep/R/keras_checkpoints/bike_checkpoints.h5", save_best_only = TRUE),
        callback_tensorboard(log_dir = "/Users/shiringlander/Documents/Github/MSHackRep/R/keras_tf_logs")
      )
    )
  
  out <- as.data.frame(model$metrics)[epochs, ] %>%
    mutate(after_epoch = epochs,
           filter_1 = filter_1,
           filter_2 = filter_2) %>%
    select(after_epoch, everything())
  
  if (i == 1) {
    out_final <- out
  } else {
    out_final <- bind_rows(out_final, out)
  }
}
```

```{r}
out_final %>%
  arrange(-acc)
```

```{r}
test_image_files_path = "/Users/shiringlander/Documents/Github/Data/Dataset_mshack/Test"

test_datagen <- image_data_generator(rescale = 1/255)

test_generator <- flow_images_from_directory(
        test_image_files_path,
        test_datagen,
        target_size = target_size,
        class_mode = 'binary')
```

```{r}
train_image_array_gen$class_indices
```

```{r}
predictions <- as.data.frame(predict_generator(model, test_generator, steps = 1))
count(predictions, V1)
```

